name: weak-event

on: [push]

jobs:
  cover:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.6]
    steps:
    - uses: actions/checkout@v1 
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Unit-Tests
      run: |
        npm install
        npm run cover
    - name: Publish to Coveralls
      uses: coverallsapp/github-action@v1.1.2 
      with:
        github-token: ${{ github.token }} 

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.6]
    steps:
    - uses: actions/checkout@v1 
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
        npm install
        npm run lint
        npm run compile
  
  name: Bump version
  on:
    push:
      branches:
        - main
      paths-ignore:
        - 'package.json'
        - 'CHANGELOG.md'
  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN_ACTION }}
      - name: Bump version
        uses: TriPSs/conventional-changelog-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN_ACTION }}
          git-message: 'chore(release): {version}'
          preset: 'angular'
          tag-prefix: ''
          output-file: 'CHANGELOG.md'